add snippets to check env variable
Signed-off-by: Nok Chan <nok.lam.chan@quantumblack.com>

diff --git a/.circleci/continue_config.yml b/.circleci/continue_config.yml
--- a/.circleci/continue_config.yml
+++ b/.circleci/continue_config.yml
@@ -18,6 +18,9 @@ parameters:
   run-build-kedro-datasets:
     type: boolean
     default: false
+  release_kedro_plugin:
+    type: boolean
+    default: false
 
 commands:
   setup_conda:
@@ -186,6 +189,9 @@ jobs:
       image: ubuntu-2004:202201-02
       docker_layer_caching: true
     steps:
+      - run:
+          name: REMOVE THIS BEFORE MERGE
+          run: python env.py
       - setup:
           python_version: <<parameters.python_version>>
           plugin: <<parameters.plugin>>
@@ -298,6 +304,38 @@ jobs:
                 command: conda activate kedro_plugins; make test-no-spark-sequential
 
 
+  publish_plugin:
+    executor:
+      name: docker
+      python_version: "3.7"
+    steps:
+      - setup
+      - add_ssh_keys
+      - run:
+          name: Check Kedro version
+          command: |
+            KEDRO_VERSION=$(./tools/circleci/github_scripts/kedro_version.py ./kedro)
+            if ./tools/circleci/check-no-version-pypi.sh "${KEDRO_VERSION}"
+            then
+                echo "export KEDRO_VERSION=\"${KEDRO_VERSION}\"" >> $BASH_ENV
+            else
+                echo "Error: Kedro version ${KEDRO_VERSION} already exists on PyPI"
+                exit 1
+            fi
+      - run:
+          name: Tag and publish release on Github
+          command: ./tools/circleci/github_scripts/release.sh kedro-org kedro ${GITHUB_TAGGING_TOKEN} ${KEDRO_VERSION}
+      - run:
+          name: Publish to PyPI
+          command: |
+            make package
+            python -m pip install twine -U
+            python -m twine upload --repository-url ${TWINE_REPOSITORY_URL} dist/*
+
+
+
+
+
 workflows:
   # when pipeline parameter, run-build-kedro-telemetry is true, the
   # kedro-telemetry job is triggered.
@@ -382,3 +420,15 @@ workflows:
               python_version: ["3.7", "3.8", "3.9", "3.10"]
       - lint:
           plugin: "kedro-datasets"
+  kedro_plugin_release:
+    when:
+      and:
+        - <<pipeline.parameters.release_kedro_plugin>>
+    jobs:
+      - build_plugin:
+          matrix:
+            parameters:
+              python_version: ["3.7", "3.8", "3.9", "3.10"]
+      - publish_kedro:
+          requires:
+            - build_plugin
